"""Full 22-driver grid with starting positions, pit strategies, and pace deltas.

pace_delta: inherent per-lap pace difference from the fastest car (P1).
Top 8 cars are closely matched (0.00-0.18s). Midfield (P9-P14) is ~0.5-0.8s slower.
Back markers (P15-P22) are 1.0-1.5s slower. This creates natural tiers so that
front-runners battle each other while the midfield stays separate.
"""

GRID = [
    # --- Front runners (P1-P8) — closely matched, all start SOFT ---
    {
        "car_number": 1,
        "driver": "Max Eriksson",
        "team": "Titan Dynamics",
        "start_position": 1,
        "pit_lap": 18,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.00,
    },
    {
        "car_number": 4,
        "driver": "Luca Novak",
        "team": "Apex Motorsport",
        "start_position": 2,
        "pit_lap": 22,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.03,
    },
    {
        "car_number": 44,
        "driver": "Sean Falconer",
        "team": "River Racing",
        "start_position": 3,
        "pit_lap": 33,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.06,
    },
    {
        "car_number": 16,
        "driver": "Carlos Vega",
        "team": "Scuderia Rossa",
        "start_position": 4,
        "pit_lap": 15,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.08,
    },
    {
        "car_number": 63,
        "driver": "Oliver Walsh",
        "team": "Sterling GP",
        "start_position": 5,
        "pit_lap": 20,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.10,
    },
    {
        "car_number": 14,
        "driver": "Fernando Reyes",
        "team": "Aston Verde",
        "start_position": 6,
        "pit_lap": 22,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.13,
    },
    {
        "car_number": 10,
        "driver": "Theo Martin",
        "team": "Alpine Force",
        "start_position": 7,
        "pit_lap": 17,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.15,
    },
    {
        "car_number": 24,
        "driver": "Valtteri Koskinen",
        "team": "Sauber Spirit",
        "start_position": 8,
        "pit_lap": 16,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.18,
    },
    # --- Midfield (P9-P14) — noticeable step in pace ---
    {
        "car_number": 55,
        "driver": "Marco Rossi",
        "team": "Scuderia Rossa",
        "start_position": 9,
        "pit_lap": 21,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.50,
    },
    {
        "car_number": 3,
        "driver": "Daniel Costa",
        "team": "Apex Motorsport",
        "start_position": 10,
        "pit_lap": 19,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.55,
    },
    {
        "car_number": 2,
        "driver": "Yuki Tanaka",
        "team": "Titan Dynamics",
        "start_position": 11,
        "pit_lap": 20,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.60,
    },
    {
        "car_number": 18,
        "driver": "Kimi Lahtinen",
        "team": "Aston Verde",
        "start_position": 12,
        "pit_lap": 23,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.65,
    },
    {
        "car_number": 77,
        "driver": "Sophie Laurent",
        "team": "River Racing",
        "start_position": 13,
        "pit_lap": 25,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.70,
    },
    {
        "car_number": 12,
        "driver": "Pierre Blanc",
        "team": "Sterling GP",
        "start_position": 14,
        "pit_lap": 24,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.75,
    },
    # --- Back markers (P15-P22) — significantly slower ---
    {
        "car_number": 31,
        "driver": "Oscar Patel",
        "team": "Alpine Force",
        "start_position": 15,
        "pit_lap": 26,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.00,
    },
    {
        "car_number": 20,
        "driver": "Kevin Andersen",
        "team": "Haas Velocity",
        "start_position": 16,
        "pit_lap": 28,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.05,
    },
    {
        "car_number": 27,
        "driver": "Nico Hoffman",
        "team": "Haas Velocity",
        "start_position": 17,
        "pit_lap": 30,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.10,
    },
    {
        "car_number": 23,
        "driver": "Li Wei",
        "team": "Sauber Spirit",
        "start_position": 18,
        "pit_lap": 27,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.15,
    },
    {
        "car_number": 6,
        "driver": "Alex Nakamura",
        "team": "Williams Heritage",
        "start_position": 19,
        "pit_lap": 29,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.20,
    },
    {
        "car_number": 8,
        "driver": "Logan Mitchell",
        "team": "Williams Heritage",
        "start_position": 20,
        "pit_lap": 32,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.25,
    },
    {
        "car_number": 22,
        "driver": "Liam O'Brien",
        "team": "Racing Bulls",
        "start_position": 21,
        "pit_lap": 25,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.30,
    },
    {
        "car_number": 21,
        "driver": "Isack Mbeki",
        "team": "Racing Bulls",
        "start_position": 22,
        "pit_lap": 31,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.35,
    },
]


def get_driver(car_number):
    """Look up a driver by car number."""
    for d in GRID:
        if d["car_number"] == car_number:
            return d
    return None
