"""Full 22-driver grid with starting positions, pit strategies, and pace deltas.

Driver/number/team pairings follow the 2025 F1 grid, with two exceptions for the
fictional hero team River Racing: John Doe (#88) and Sophie Laurent (#77). Team
names are intentionally fictional but each pairs the real 2025 team-mates.

pace_delta: inherent per-lap pace difference from the fastest car (P1).
Top 8 cars are closely matched (0.00-0.18s). Midfield (P9-P14) is ~0.5-0.8s slower.
Back markers (P15-P22) are 1.0-1.5s slower. This creates natural tiers so that
front-runners battle each other while the midfield stays separate.
"""

GRID = [
    # --- Front runners (P1-P8) — closely matched, all start SOFT ---
    {
        "car_number": 1,
        "driver": "Max Verstappen",
        "team": "Titan Dynamics",
        "start_position": 1,
        "pit_lap": 18,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.00,
    },
    {
        "car_number": 4,
        "driver": "Lando Norris",
        "team": "Apex Motorsport",
        "start_position": 2,
        "pit_lap": 22,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.03,
    },
    {
        "car_number": 88,
        "driver": "John Doe",
        "team": "River Racing",
        "start_position": 3,
        "pit_lap": 33,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.06,
    },
    {
        "car_number": 16,
        "driver": "Charles Leclerc",
        "team": "Scuderia Rossa",
        "start_position": 4,
        "pit_lap": 15,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.08,
    },
    {
        "car_number": 63,
        "driver": "George Russell",
        "team": "Sterling GP",
        "start_position": 5,
        "pit_lap": 20,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.10,
    },
    {
        "car_number": 14,
        "driver": "Fernando Alonso",
        "team": "Aston Verde",
        "start_position": 6,
        "pit_lap": 22,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.13,
    },
    {
        "car_number": 10,
        "driver": "Pierre Gasly",
        "team": "Alpine Force",
        "start_position": 7,
        "pit_lap": 17,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.15,
    },
    {
        "car_number": 44,
        "driver": "Lewis Hamilton",
        "team": "Scuderia Rossa",
        "start_position": 8,
        "pit_lap": 16,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.18,
    },
    # --- Midfield (P9-P14) — noticeable step in pace ---
    {
        "car_number": 55,
        "driver": "Carlos Sainz",
        "team": "Williams Heritage",
        "start_position": 9,
        "pit_lap": 21,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.50,
    },
    {
        "car_number": 81,
        "driver": "Oscar Piastri",
        "team": "Apex Motorsport",
        "start_position": 10,
        "pit_lap": 19,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.55,
    },
    {
        "car_number": 30,
        "driver": "Liam Lawson",
        "team": "Racing Bulls",
        "start_position": 11,
        "pit_lap": 20,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.60,
    },
    {
        "car_number": 18,
        "driver": "Lance Stroll",
        "team": "Aston Verde",
        "start_position": 12,
        "pit_lap": 23,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.65,
    },
    {
        "car_number": 77,
        "driver": "Sophie Laurent",
        "team": "River Racing",
        "start_position": 13,
        "pit_lap": 25,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.70,
    },
    {
        "car_number": 12,
        "driver": "Kimi Antonelli",
        "team": "Sterling GP",
        "start_position": 14,
        "pit_lap": 24,
        "pit_tire": "MEDIUM",
        "start_tire": "SOFT",
        "pace_delta": 0.75,
    },
    # --- Back markers (P15-P22) — significantly slower ---
    {
        "car_number": 31,
        "driver": "Esteban Ocon",
        "team": "Haas Velocity",
        "start_position": 15,
        "pit_lap": 26,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.00,
    },
    {
        "car_number": 87,
        "driver": "Oliver Bearman",
        "team": "Haas Velocity",
        "start_position": 16,
        "pit_lap": 28,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.05,
    },
    {
        "car_number": 27,
        "driver": "Nico Hulkenberg",
        "team": "Sauber Spirit",
        "start_position": 17,
        "pit_lap": 30,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.10,
    },
    {
        "car_number": 23,
        "driver": "Alexander Albon",
        "team": "Williams Heritage",
        "start_position": 18,
        "pit_lap": 27,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.15,
    },
    {
        "car_number": 6,
        "driver": "Isack Hadjar",
        "team": "Racing Bulls",
        "start_position": 19,
        "pit_lap": 29,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.20,
    },
    {
        "car_number": 5,
        "driver": "Gabriel Bortoleto",
        "team": "Sauber Spirit",
        "start_position": 20,
        "pit_lap": 32,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.25,
    },
    {
        "car_number": 22,
        "driver": "Yuki Tsunoda",
        "team": "Titan Dynamics",
        "start_position": 21,
        "pit_lap": 25,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.30,
    },
    {
        "car_number": 7,
        "driver": "Jack Doohan",
        "team": "Alpine Force",
        "start_position": 22,
        "pit_lap": 31,
        "pit_tire": "HARD",
        "start_tire": "SOFT",
        "pace_delta": 1.35,
    },
]


def get_driver(car_number):
    """Look up a driver by car number."""
    for d in GRID:
        if d["car_number"] == car_number:
            return d
    return None
