version: 2

sources:
  - name: river_racing
    schema: RIVER-RACING-PROD-CLUSTER
    tables:
      - name: car_telemetry
        config:
          materialized: streaming_source
      - name: race_standings
        config:
          materialized: streaming_source
